#cloud-config
bootcmd:
  - yum install -y git
  - yum install -y python3-pip
  - pip3 install ansible
  - /usr/local/bin/ansible-pull -U $(curl --silent http://169.254.169.254/latest/meta-data/tags/instance/repoURL) --full -C $(curl --silent http://169.254.169.254/latest/meta-data/tags/instance/appVer) apprun/$(curl --silent http://169.254.169.254/latest/meta-data/tags/instance/appRole).yml