---
# This playbook prints a simple debug message
- name: Echo
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Mark node info
    ansible.builtin.file:
      path: /clusterB.txt
      state: touch
  - name: Print debug message
    debug:
      msg: Hello, world!